-- ENREGISTREMENTS :

CREATE TABLE MOVIES
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       NVARCHAR(140) NOT NULL,
    duration    int      NOT NULL,
    release     SMALLINT NOT NULL,
    synopsis    NVARCHAR(140),
    director_id int      NOT NULL,
    genre_id    int      NOT NULL
);

CREATE TABLE GENRES
(
    id    int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title NVARCHAR(140) NOT NULL
);

CREATE TABLE REVIEWS
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating   int NOT NULL,
    comment  NVARCHAR(140),
    user_id  int NOT NULL,
    movie_id int NOT NULL
);

CREATE TABLE CASTMEMBERS
(
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name NVARCHAR(140) NOT NULL,
    last_name  NVARCHAR(140) NOT NULL
);

CREATE TABLE ACTORS
(
    movie_id int NOT NULL,
    cast_id  int NOT NULL,
    PRIMARY KEY (movie_id, cast_id)
)

CREATE TABLE REGISTERED_USERS
(
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name NVARCHAR(140) NOT NULL,
    last_name  NVARCHAR(140) NOT NULL,
    email      NVARCHAR(140) NOT NULL,
    password   NVARCHAR(140) NOT NULL,
    is_admin   BOOLEAN
);


ALTER TABLE MOVIES
    add constraint fk_CASTMEMBERS_DIR_MOVIES foreign key (director_id) references CASTMEMBERS (id);
ALTER TABLE MOVIES
    add constraint fk_CASTMEMBERS_GENRE_MOVIES foreign key (genre_id) references GENRES (id);
ALTER TABLE REVIEWS
    add constraint fk_REGISTERED_USERS_REVIEWS foreign key (user_id) references REGISTERED_USERS (id);
ALTER TABLE REVIEWS
    add constraint fk_MOVIES_REVIEWS foreign key (movie_id) references MOVIES (id);
ALTER TABLE ACTORS
    add constraint fk_MOVIES_ACTORS foreign key (movie_id) references MOVIES (id);
ALTER TABLE ACTORS
    add constraint fk_CASTMEMBERS_ACTORS foreign key (cast_id) references CASTMEMBERS (id);

--Insère des enregistrements dans la table GENRES
INSERT INTO GENRES (title)
VALUES ('Animation');
INSERT INTO GENRES (title)
VALUES ('Science-fiction');
INSERT INTO GENRES (title)
VALUES ('Documentaire');
INSERT INTO GENRES (title)
VALUES ('Action');
INSERT INTO GENRES (title)
VALUES ('Comédie');
INSERT INTO GENRES (title)
VALUES ('Drame');
INSERT INTO GENRES (title)
VALUES ('Policier');
INSERT INTO GENRES (title)
VALUES ('Horreur');



--Insère des enregistrements dans la table CASTMEMBERS
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Spielberg', 'Steven');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Cronenberg', 'David');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Boon', 'Dany');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Attenborough', 'Richard');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Goldblum', 'Jeff');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Davis', 'Geena');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Rylance', 'Mark');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Barnhill', 'Ruby');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Merad', 'Kad');
INSERT INTO CASTMEMBERS (last_name, first_name)
VALUES ('Gans', 'Christophe');


--Insère des enregistrements dans la table REGISTERED_USERS
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password)
VALUES ('abaille@campus-eni.fr', 'BAILLE', 'Anne-Lise',
        '{bcrypt}$1a$00$KaSHgvH9p/cUnsOVPzYvzunWDAIv57whrOxmui0S.0AjzbP4RX6yO');/*Mot de Passe = annelise*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password)
VALUES ('jtrillard@campus-eni.fr', 'TRILLARD', 'Julien',
        '{bcrypt}$1a$00$VwQ6gMUPLeQnFC5vCsOoTevzdPe.JPu0L/6cwPGdJ5TjSpipGwY.y');/*Mot de Passe = julien*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password)
VALUES ('fdelaschesnais@campus-eni.fr', 'DELACHESNAIS', 'Frédéric',
        '{bcrypt}$1a$00$GhRo7SeZhL53e6E6/DQ2Le4mgkAjuesQCjQptJFh0oQLjwdeH9ZWG');/*Mot de Passe = frederic*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password, is_admin)
VALUES ('pmontembault@campus-eni.fr', 'MONTEMBAULT', 'Philippe',
        '{bcrypt}$1a$00$0g2xzuioWFxQLVdmc7LRKOb.sVxyH/uQQjdNg.CPX6tg2cYRK2VTe', 0);/*Mot de Passe = philippe*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password)
VALUES ('hbernard@campus-eni.fr', 'BERNARD', 'Hervé',
        '{bcrypt}$1a$00$oYzLsRNezWP.ruY72rkYAuUH03nuNv245V2z2O3pRkuA.GwaXNGke');/*Mot de Passe = herve*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password)
VALUES ('tgroussard@campus-eni.fr', 'GROUSSARD', 'Thierry',
        '{bcrypt}$1a$00$ca.IC7NI1Km2kRRUoZ9EeORDJMPPe0iyyYShQ0IqPswr4YXDLqwey');/*Mot de Passe = thierry*/
INSERT INTO REGISTERED_USERS (email, last_name, first_name, password, is_admin)
VALUES ('sgobin@campus-eni.fr', 'GOBIN', 'Stéphane',
        '{bcrypt}$1a$00$B4U19ajHsIKd7aY2c/JNn.xTJpOCAeoXvT9XvfzbbHGP3iIFV9Lkm', 0);
/*Mot de Passe = stephane*/


--Insère des enregistrements dans la table MOVIE
INSERT INTO MOVIES (title, release, duration, synopsis, director_id, genre_id)
VALUES ('Jurassic Park', 0992, 017,
        'Le film raconte l''histoire d''un milliardaire et son équipe de généticiens parvenant à ramener à la vie des dinosaures grâce au clonage.',
        0, 1);
INSERT INTO MOVIES (title, release, duration, synopsis, director_id, genre_id)
VALUES ('The Fly', 0975, 94,
        'Il s''agit de l''adaptation cinématographique de la nouvelle éponyme de l''auteur George Langelaan.', 1, 1);
INSERT INTO MOVIES (title, release, duration, synopsis, director_id, genre_id)
VALUES ('The BFG', 1005, 06, 'Le Bon Gros Géant est un géant bien différent des autres habitants du Pays des Géants.',
        0, 4);
INSERT INTO MOVIES (title, release, duration, synopsis, director_id, genre_id)
VALUES ('Bienvenue chez les Ch''tis', 1007, 005,
        'Philippe Abrams marié à Julie (dépressive) essaie d''être mutaté dans le Sud. Il se retrouve à Bergues dans le Nord.',
        2, 4);
INSERT INTO MOVIES (title, release, duration, synopsis, director_id, genre_id)
VALUES ('Le Pacte des Loups', 1000, 010,
        '',9, 6);


--Insère des enregistrements dans la table de jointure avec MOVIE - ACTORS
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (0, 3);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (0, 4);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (1, 4);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (1, 5);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (2, 6);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (2, 7);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (3, 2);
INSERT INTO ACTORS (movie_id, cast_id)
VALUES (3, 8);


--Insère des enregistrements dans la table de AVIS
INSERT INTO REVIEWS (rating, comment, user_id, movie_id)
VALUES (3, 'On rit du début à la fin', 0, 3);


-- Requetes pour aider à tester
/*
select * from GENRES;
select * from CASTMEMBERS;
select * from REGISTERED_USERS;

select * from MOVIE;

select f.*, g.title as Genre, (r.first_name + ' ' +r.last_name)as Realisateur  from Film f
	inner join genre g on f.genre_id=g.id
	inner join CASTMEMBERS r on r.id = f.director_id;
select * from ACTORS;

select f.*, (p.first_name + ' '+ p.last_name) as Acteur from MOVIE f
	inner join ACTORS a on a.movie_id = f.id
	inner join CASTMEMBERS p on a.cast_id = p.id;

select * from AVIS;

*/
